# workflow:
#   rules: 
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

default:
  image: 'rust:slim'

build:
  script:
    - cargo build

test: 
  script:
    - cargo test

publish:
  variables:
    CARGO_TOKEN: $CARGO_TOKEN
    HELLO: $TEST
    TEST: sinfsdafj
  script:
    - echo "${TEST}"
    - export CARGO_REGISTRY_TOKEN=$CARGO_TOKEN
    - cargo publish

