build:
  stage: build
  script:
    - echo "testing ci pipeline"

test: 
  stage: test
  script:
    - echo "testing the application"

publish:
  stage: deploy
  script:
    - echo "publishing the application to crates.io"

