# workflow:
#   rules: 
#     - if: '$CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main"'

default:
  image: 'rust:slim'

build:
  stage: build
  script:
    - cargo build

test: 
  stage: test
  script:
    - cargo test

publish:
  stage: deploy
  script:
    - export CARGO_REGISTRY_TOKEN=$CARGO_TOKEN
    - cargo publish


