name: Docker

on:
    push:
        branches: ["main", "feature/docker"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: hustcer/setup-nu@v3

            - name: Get Cargo version
              run: version=$(nu -c "cargo metadata --format-version=1 --no-deps | from json | get packages | first | get version")
            - name: Build docker image
              run: docker build -t docki:$version .
