name: Docker

on:
    push:
        branches: ["main"]
        # paths:
        #   - 'Cargo.toml'
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            packages: write
            contents: read
            attestations: write
            id-token: write

        steps:
            - uses: actions/checkout@v4
            - uses: hustcer/setup-nu@v3
            - uses: cachix/install-nix-action@v31
              with:
                  nix_path: nixpkgs=channel:nixos-unstable

            - run: nix build .#docker
            - run: docker load -i result
            - run: export CARGO_VERSION=$(cargo metadata --format-version=1 --no-deps | from json | get packages | first | get version)
            - name: Log in to registry
              run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            - run: docker tag docki:latest ghcr.io/quirinecker/docki/docki:$CARGO_VERSION
            - run: docker push docki:$CARGO_VERSION
