name: Docker

on:
    push:
        branches: ["main", "feature/docker"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - uses: hustcer/setup-nu@v3
              with:
                  version: "0.90" # Don't use 0.90 here, as it would be a float number and would be converted to 0.9, you can use v0.90/0.90.0 or '0.90'
            - name: Build Docker image
              run: |
                  apt install -y nu
                  version=$(nu -c "cargo metadata --format-version=1 --no-deps | from json | get packages | first | get version")
                  echo $version
            - name: Run tests
              run: cargo test --verbose
            - name: Publish to crates.io
              env:
                  CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
              run: |
                  cargo publish --verbose
